baseline: Your blogging assistant.
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ''
keywords: 'Cecil, Static Site Generator, SSG'
author: Arnaud Ligny
title: Nilson Jacques
description: 'A place to record the random tips, tricks, and cool tech I come across.'
baseurl: /
canonicalurl: true
date:
  format: j F Y
  timezone: GMT
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
optimize:
  enabled: true
